version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000" # Mapeia a porta 3000 do container para a porta 3001 do host
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devsecops
    ports:
      - "5432:5432"